### ISSUE TITLE
Unable to initialize the MySQL database

### ISSUE THREAD

**Issue by NiklausHofer** [puzzle/cryptopus#679]
Following the instructions in the wiki (https://github.com/puzzle/cryptopus/wiki/Docker) I am unable to initialize the database:
```bash
bundle exec rake db:setup
```
```
I, [2023-02-24T14:39:44.538171 #29]  INFO -- : Raven 3.1.2 configured not to capture errors: DSN not set
D, [2023-02-24T14:39:44.737117 #29] DEBUG -- :    (0.4ms)  CREATE DATABASE `cryptopus_prod` DEFAULT CHARACTER SET `utf8`
Database 'cryptopus_prod' already exists
D, [2023-02-24T14:39:44.788449 #29] DEBUG -- :    (0.5ms)  DROP TABLE IF EXISTS `encryptables` CASCADE
D, [2023-02-24T14:39:44.790033 #29] DEBUG -- :    (0.6ms)  CREATE TABLE `encryptables` (`id` bigint NOT NULL AUTO_INCREMENT PRIMARY KEY, `name` varchar(255) DEFAULT '' NOT NULL, `folder_id` int, `description` text, `created_at` datetime NOT NULL, `updated_at` datetime NOT NULL, `tag` varchar(255), `type` varchar(255) DEFAULT 'Account::Credentials' NOT NULL, `encrypted_data` mediumtext, `credential_id` int, `content_type` text, INDEX `index_encryptables_on_description` (`description`), INDEX `index_encryptables_on_name` (`name`), INDEX `index_encryptables_on_tag` (`tag`))
D, [2023-02-24T14:39:44.790144 #29] DEBUG -- : Mysql2::Error: BLOB/TEXT column 'description' used in key specification without a key length excluded from capture: DSN not set
rake aborted!
ActiveRecord::StatementInvalid: Mysql2::Error: BLOB/TEXT column 'description' used in key specification without a key length
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:325:in `create_table'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:931:in `block in method_missing'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:899:in `block in say_with_time'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:899:in `say_with_time'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:920:in `method_missing'
/app-src/db/schema.rb:14:in `block in <top (required)>'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/schema.rb:55:in `instance_eval'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/schema.rb:55:in `define'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/schema.rb:50:in `define'
/app-src/db/schema.rb:13:in `<top (required)>'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:374:in `load'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:374:in `load_schema'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:477:in `block in load_schema_current'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:552:in `block (2 levels) in each_current_configuration'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:549:in `each'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:549:in `block in each_current_configuration'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:548:in `each'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:548:in `each_current_configuration'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:476:in `load_schema_current'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/railties/databases.rake:469:in `block (3 levels) in <top (required)>'
/app-src/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'

Caused by:
Mysql2::Error: BLOB/TEXT column 'description' used in key specification without a key length
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `_query'
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:131:in `block in query'
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `handle_interrupt'
/app-src/vendor/bundle/ruby/3.0.0/gems/mysql2-0.5.3/lib/mysql2/client.rb:130:in `query'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:632:in `block (2 levels) in raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:631:in `block in raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:765:in `block in log'
/app-src/vendor/bundle/ruby/3.0.0/gems/activesupport-7.0.2.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_adapter.rb:756:in `log'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:630:in `raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:96:in `raw_execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/mysql/database_statements.rb:47:in `execute'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/abstract/schema_statements.rb:325:in `create_table'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/connection_adapters/mysql/schema_statements.rb:81:in `create_table'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:931:in `block in method_missing'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:899:in `block in say_with_time'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:899:in `say_with_time'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/migration.rb:920:in `method_missing'
/app-src/db/schema.rb:14:in `block in <top (required)>'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/schema.rb:55:in `instance_eval'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/schema.rb:55:in `define'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/schema.rb:50:in `define'
/app-src/db/schema.rb:13:in `<top (required)>'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:374:in `load'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:374:in `load_schema'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:477:in `block in load_schema_current'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:552:in `block (2 levels) in each_current_configuration'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:549:in `each'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:549:in `block in each_current_configuration'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:548:in `each'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:548:in `each_current_configuration'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/tasks/database_tasks.rb:476:in `load_schema_current'
/app-src/vendor/bundle/ruby/3.0.0/gems/activerecord-7.0.2.3/lib/active_record/railties/databases.rake:469:in `block (3 levels) in <top (required)>'
/app-src/vendor/bundle/ruby/3.0.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:478:in `exec'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:31:in `dispatch'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/cli.rb:25:in `start'
/usr/local/bundle/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.2.32/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => db:setup => db:schema:load
(See full trace by running task with --trace)
```

**Comment by mtnstar** [comment]
looks like there's an issue with the current mysql server and the db migrations. we might have a look in the next two Weeks. 

we completely switched to postgresql, would that be an option for you at the moment? or just use sqlite?

**Comment by NiklausHofer** [comment]
Going PostgreSQL would certainly be an option, especially if this is the the main focus of development going forward anyway. Unfortunately the documentation for the PostgreSQL set-up is rather lacking compared to the documentation for the MySQL set-up.

I assume the docker bring-up process is pretty much the same?

**Comment by mtnstar** [comment]
Rehi

since we do not really want to support Mysql anymore, I updated the setup manual for Postgresql:

https://github.com/puzzle/cryptopus/wiki/Docker#run-with-postgresql

would be nice if you could verify if this is working :)

**Comment by NiklausHofer** [comment]
I was able to start the container, connect and log-in. Thank you for the quick reaction!
